- name: Create a Django app
  hosts: localhost
  tasks:
    - include_vars:
        file: "./cookiecutter/cookiecutter-config.yml"
        name: cc
    - name: Basic variable setup
      set_fact:
        django_project_slug: "{{ cc.default_context.project_slug }}"
        django_project_name: "{{ cc.default_context.project_name }}"
        pycharm_project_folder: /Users/luiscberrocal/PycharmProjects
        templates_source: './templates/model_templates/model_list.html.j2'
    - name: Setup destination
      set_fact:
        templates_destination: './output/{{ model_name | to_snake_case }}_list.html'
    - name: Create templates {{ model_name | to_snake_case }}_list.html
      template:
        src: '{{ templates_source }}'
        dest: "{{ pycharm_project_folder }}/{{django_project_slug}}/{{django_project_slug}}/templates/{{ django_app_name }}/{{ model_name | to_snake_case }}_list.html"



