- name: Create a Django app
  hosts: localhost
  tasks:
    - name: Basic variable setup
      set_fact:
        pycharm_project_folder: "{{ansible_facts.env.HOME}}/PycharmProjects"
        templates_source: './templates/django_app_name'
    - name: Setup destination
      set_fact:
        templates_destination: "{{ pycharm_project_folder }}/{{django_project_slug}}/{{django_project_slug}}/{{ django_app_name }}"
    - name: Ensure directory structure exists
      file:
        path: '{{ templates_destination }}/{{ item.path }}'
        state: directory
      with_filetree: '{{templates_source}}'
      when: item.state == 'directory'
    - name: Ensure files are populated from templates
      template:
        src: '{{ item.src }}'
        dest: '{{ templates_destination }}/{{ item.path }}'
      with_filetree: '{{ templates_source }}'
      when: item.state == 'file'



