- name: Django ansible playbook
  hosts: localhost
  tasks:
    - include_vars:
        file: "./cookiecutter/cookiecutter-config.yml"
        name: cc
    - include_vars:
        file: "./.secrets/credentials.yml"
        name: credentials
    - name: Setting facts
      set_fact:
        django_project_slug: ""
        django_project_name: ""
        pycharm_project_folder: "/Users/luiscberrocal/PycharmProjects"
    - name: Setting folders
      set_fact:
        ansible_project_folder: "{{ pycharm_project_folder }}/django_ansible_config"
        django_project_folder: "{{ pycharm_project_folder }}/{{ django_project_slug }}"
        github_repo: "https://github.com/luiscberrocal/{{django_project_slug}}.git"
        github_token_file: "{{ pycharm_project_folder }}/django_ansible_config/.secrets/github_token.txt"
        aws_staging_bucket: "{{ django_project_slug | replace('_','-') }}-staging-bucket"
        aws_staging_user: "{{ django_project_slug | replace('_','-') }}-staging-user"
        aws_staging_group: "{{ django_project_slug | replace('_','-') }}-staging-group"
    - name: Heroku Superuser for staging
      include_tasks: ./tasks/heroku_superuser.yml
      when: 1 == 1




