- name: Django ansible playbook
  hosts: localhost
  tasks:
    - name: Current installation user.
      user:
        name: luiscberrocal
        state: present
      register: current_user_data
    - include_vars:
        file: "./.secrets/credentials.yml"
        name: credentials
    - name: Setting facts
      set_fact:
        pycharm_project_folder: "{{current_user_data.home}}/PycharmProjects"
    - name: Setting folders
      set_fact:
        ansible_project_folder: "{{ pycharm_project_folder }}/django_ansible_config"
        django_project_folder: "{{ pycharm_project_folder }}/{{ django_project_slug }}"
        github_repo: "https://github.com/luiscberrocal/{{django_project_slug}}.git"
        github_token_file: "{{ pycharm_project_folder }}/django_ansible_config/.secrets/github_token.txt"
        aws_staging_bucket: "{{ django_project_slug | replace('_','-') }}-staging-bucket"
        aws_staging_user: "{{ django_project_slug | replace('_','-') }}-staging-user"
        aws_staging_group: "{{ django_project_slug | replace('_','-') }}-staging-group"
        database_backup_folder: "{{current_user_data.home}}/Dropbox/Temp"

    - name: Setting up cookiecutter for {{django_project_slug}}
      set_fact:
        cookiecutter_config: "{{ ansible_project_folder }}/cookiecutter/cookiecutter-config.yml"
    - name: Create django project
      include_tasks: ./tasks/django_project.yml
      when: 1 == 1
    - name: Configure django super user
      include_tasks: ./tasks/django_user_config.yml
      when: 1 == 2
    - name: Add python scripts
      include_tasks: ./tasks/python_scripts.yml
      when: 1 == 2
    - name: Git local setup
      include_tasks: ./tasks/git_setup.yml
      when: 1 == 2
    - name: AWS Configuration
      include_tasks: ./tasks/aws_config.yml
      when: 1 == 3
    - name: Heroku Configuration
      include_tasks: ./tasks/heroku_config.yml
      when: 1 == 3
#    - name: Heroku Superuser for stating
#      include_tasks: ./tasks/heroku_superuser.yml
#      when: 1 == 1
    - name: Crete github repo
      include_tasks: ./tasks/github_repo.yml
      when: 1 == 3



