- name: Django ansible play book
  hosts: localhost
  vars:
    pycharm_project_folder: /Users/luiscberrocal/PycharmProjects
    django_project_slug: rec_promoter_app
    django_project_folder: "{{ pycharm_project_folder }}/{{ django_project_slug }}"
    cookiecutter_config: "{{ pycharm_project_folder }}/django_ansible_config/cookiecutter/cookiecutter-config.yml"
  tasks:
    - name: Create django project
      include_tasks: ./tasks/django_project.yml


