- name: Django ansible playbook
  hosts: localhost
  tasks:
    - name: Current installation user.
      user:
        name: luiscberrocal
        state: present
      register: current_user_data
    - include_vars:
        file: "./.secrets/credentials.yml"
        name: credentials
    - name: Setting facts
      set_fact:
        pycharm_project_folder: "{{current_user_data.home}}/PycharmProjects"
    - name: Setting folders
      set_fact:
        do_local_tasks: 'yes'
        do_cloud_tasks: 'no'
        ansible_project_folder: "{{ pycharm_project_folder }}/django_ansible_config"
        django_project_folder: "{{ pycharm_project_folder }}/{{ django_project_slug }}"
        github_repo: "https://github.com/luiscberrocal/{{django_project_slug}}.git"
        github_token_file: "{{ pycharm_project_folder }}/django_ansible_config/.secrets/github_token.txt"
        aws_staging_bucket: "{{ django_project_slug | replace('_','-') }}-staging-bucket"
        aws_staging_user: "{{ django_project_slug | replace('_','-') }}-staging-user"
        aws_staging_group: "{{ django_project_slug | replace('_','-') }}-staging-group"
        database_backup_folder: "{{current_user_data.home}}/Dropbox/Temp"

    - name: Setting up cookiecutter for {{django_project_slug}}
      set_fact:
        cookiecutter_config: "{{ ansible_project_folder }}/cookiecutter/cookiecutter-config.yml"
    - name: Create django project with Cookiecutter (cookiecutter)
      include_tasks: ./tasks/0100_django_project_cookiecutter.yml
      when: do_local_tasks == True and not skip_cookiecutter is defined
    - name: Configure django configuration (django_config)
      include_tasks: ./tasks/0200_django_user_config.yml
      when: do_local_tasks == True and not skip_django_config is defined
    - name: Add python scripts
      include_tasks: ./tasks/0300_python_scripts.yml (scripts)
      when: do_local_tasks == True and not skip_scripts is defined
    - name: Git local setup
      include_tasks: ./tasks/0400_git_setup.yml (git_setup)
      when: do_local_tasks == True and not skip_git_setup is defined
    - name: AWS Configuration
      include_tasks: ./tasks/1100_aws_config.yml
      when: 1 == 3
    - name: Heroku Configuration
      include_tasks: ./tasks/1200_heroku_config.yml
      when: 1 == 3
#    - name: Heroku Superuser for stating
#      include_tasks: ./tasks/heroku_superuser.yml
#      when: 1 == 1
    - name: Crete github repo
      include_tasks: ./tasks/1300_github_repo.yml
      when: 1 == 3



