- name: Prapare secets folder
  hosts: localhost
  tasks:
    - include_vars:
        file: "./cookiecutter/cookiecutter-config.yml"
        name: cc

    - name: Setting facts
      set_fact:
        dev_username: "{{ cc.default_context.github_username }}"
        dev_pwd: "{{ pwd }}"
        dev_email: "{{ cc.default_context.email }}"
        staging_username: "{{ cc.default_context.github_username }}"
        staging_pwd: "{{ pwd }}"
        staging_email: "{{ cc.default_context.email }}"
    - name: Create .secrets folder
      file:
        path: "./.secrets"
        state: directory
    - template:
        src: "./templates/credentials.yml.j2"
        dest: "./.secrets/credentials.yml"