- name: Reset local environment
  hosts: localhost
  tasks:
    - include_vars:
        file: "./cookiecutter/cookiecutter-config.yml"
        name: cc
    - set_fact:
        django_project_slug: "{{ cc.default_context.project_slug }}"
        django_project_name: "{{ cc.default_context.project_name }}"
        pycharm_project_folder: /Users/luiscberrocal/PycharmProjects
    - debug:
        msg: "{{ django_project_slug }}"
    - name: Delete directory
      file:
        path: "{{pycharm_project_folder}}/{{django_project_slug}}"
        state: absent
    - name: Stop all containers
      shell: docker stop $(docker ps -qa)
# docker ps -a | awk '{ print $1,$2 }' | grep rec_promoter_app | awk '{print $1 }' | xargs -I {} docker rm {}
    - name: Get postgres container line
      shell: "docker ps -a | grep {{django_project_slug}}_production"
      register: results
      failed_when: results.rc >= 2

    - name: Get post container id
      set_fact:
        postgres_container: "{{ results.stdout | regex_search(regexp,'\\1') | first }}"
      vars:
        regexp: '([a-z0-9]{12})\s+'
      when: results.stdout | length > 0
    - name: Delete postgres image
      shell: "docker rm {{postgres_container}}"
      when: results.stdout | length > 0
    - name: Delete volume
      shell: "docker volume rm {{django_project_slug}}_local_postgres_data"
    - name: Delete backups volume
      shell: "docker volume rm {{django_project_slug}}_local_postgres_data_backups"


