- name: Test Django ansible play book
  hosts: localhost
  vars:
    pycharm_project_folder: /Users/luiscberrocal/PycharmProjects
    ansible_project_folder: "{{ pycharm_project_folder }}/django_ansible_config"
    django_project_slug: rec_promoter_app
    django_project_folder: "{{ pycharm_project_folder }}/{{ django_project_slug }}"
    cookiecutter_config: "{{ ansible_project_folder }}/cookiecutter/cookiecutter-config.yml"
    github_repo: "https://github.com/luiscberrocal/{{django_project_slug}}.git"
    github_token_file: "{{ pycharm_project_folder }}/django_ansible_config/.secrets/github_token.txt"
  tasks:

    - name: Test that my module works
      update_version:
      register: result

    - debug: var=result