- name: Run cookie cutter
  shell: "cookiecutter --no-input https://github.com/luiscberrocal/cookiecutter-django --checkout develop --config-file {{ cookiecutter_config }}"
  args:
    chdir: "{{ pycharm_project_folder }}"