#- include_vars:
#    file: /home/vagrant/stunnelSimAnsPractice/roles/ns16/vars/customers.yml
#    name: customers

- template:
    src: "{{ ansible_project_folder }}/files/setup.cfg.j2"
    dest: "{{ ansible_project_folder }}/files/setup_temp.cfg"

- name: "Append setup.cfg with bumpversion configuration"
  shell: cat {{ ansible_project_folder }}/files/setup_temp.cfg >> setup.cfg
  args:
    chdir: "{{ django_project_folder }}"

- name: "Delete temporary file"
  file:
    path: "{{ ansible_project_folder }}/files/setup_temp.cfg"
    state: absent

- name: Adds version to base.html
  update_version:
    base_html: "{{ django_project_folder }}/{{django_project_slug}}/templates/base.html"
  #register: result

- name: Ensure TEST_OUTPUT_PATH is set
  lineinfile:
    path: "{{ django_project_folder }}/config/settings/base.py"
    insertafter: '^APPS_DIR\s*=\s*'
    regexp: '^TEST_OUTPUT_PATH\s*=\s*'
    line: 'TEST_OUTPUT_PATH = ROOT_DIR/"output"'

- name: Ensure output folder is ignored by git
  lineinfile:
    path: "{{ django_project_folder }}/.gitignore"
    regexp: '^output\/$'
    line: 'output/'


- name: Adding translation import to base.py
  lineinfile:
    path: "{{ django_project_folder }}/config/settings/base.py"
    insertafter: '^import\senviron'
    regexp: '^from\sdjango\.utils\.translation\simport\sugettext_lazy\sas\s_'
    line: 'from django.utils.translation import ugettext_lazy as _'

- name: Adding languages to base.py
  blockinfile:
    block: "{{ lookup('file', '../files/settings.py') }}"
    path: "{{ django_project_folder }}/config/settings/base.py"