- name: Stop all containers
  shell: docker stop $(docker ps -qa)
  args:
    chdir: "{{ django_project_folder }}"

- name: Build containers from {{ django_project_folder }}/local.yml
  shell: docker-compose -f local.yml build
  args:
    chdir: "{{ django_project_folder }}"

- name: Run migrations
  shell: docker-compose -f local.yml run django python manage.py migrate
  args:
    chdir: "{{ django_project_folder }}"

- name: Create super user
  shell: "docker-compose -f local.yml run -e DJANGO_SUPERUSER_USERNAME={{credentials.dev.username}} -e DJANGO_SUPERUSER_EMAIL={{credentials.dev.email}} -e DJANGO_SUPERUSER_PASSWORD={{credentials.dev.pwd}} django python manage.py createsuperuser --no-input"
  args:
    chdir: "{{ django_project_folder }}"

- name: Create messages for spanish
  shell: "docker-compose -f local.yml run django python manage.py makemessages -l es"
  args:
    chdir: "{{ django_project_folder }}"

- name: Compile messages for spanish
  shell: "docker-compose -f local.yml run django python manage.py compilemessages"
  args:
    chdir: "{{ django_project_folder }}"

- name: Run Django tests
  shell: "docker-compose -f local.yml run django python manage.py test"
  args:
    chdir: "{{ django_project_folder }}"

- name: Run Pytest tests
  shell: "docker-compose -f local.yml run django pytest"
  args:
    chdir: "{{ django_project_folder }}"