- name: Get stats of the .git folder
  ansible.builtin.stat:
    path: "{{ django_project_folder }}/.git"
  register: git_folder

- name: Init the git repo
  shell: git init
  args:
    creates: .init
    chdir: "{{ django_project_folder }}"
  when: not git_folder.stat.exists

#- name: Add remote to repo
#  shell: git remote add origin {{ github_repo }}
#  args:
#    chdir: "{{ django_project_folder }}"