- name: Get stats of the .git folder
  stat:
    path: "{{ django_project_folder }}/.git"
    register: git_folder
#     - debug:
#         msg: {{ git_folder.stat }}
- name: Init the git repo
  shell: git init
  args:
    creates: .init
    chdir: "{{ django_project_folder }}"
  when: not git_folder.stat.exists
- name: Add remote to repo
  shell: git remote add origin https://github.com/user/repo.git