
#- name: Create heroku staging app
#  shell: heroku apps:create {{ django_project_slug | replace('_','-') }}-staging
#  args:
#    chdir: "{{ django_project_folder }}"

#- name: Create heroku postgres database
#  shell: heroku addons:create heroku-postgresql:hobby-dev
#  args:
#    chdir: "{{ django_project_folder }}"

#- name: Create heroku redis
#  shell: heroku addons:create heroku-redis:hobby-dev -a {{ django_project_slug | replace('_','-') }}-staging
#  args:
#    chdir: "{{ django_project_folder }}"

- name: Create heroku mailgun
  shell: heroku addons:create mailgun:starter
  args:
    chdir: "{{ django_project_folder }}"

#DJANGO_SECRET_KEY
#DJANGO_AWS_ACCESS_KEY_ID
#DJANGO_AWS_SECRET_ACCESS_KEY
#DJANGO_AWS_STORAGE_BUCKET_NAME
# DJANGO_ADMIN_URL
# ENVIRONMENT_ADMIN_CSS
# ENVIRONMENT_NAME
# USE_DOCKER