default_context:
    full_name: "Luis C. Berrocal"
    email: "luis.berrocal.1942@gmail.com"
    github_username: "luiscberrocal"
    project_name: "REC Demo"
    project_slug: "rec_demo"
    domain_name: "herokuapp.com"
    version: "0.1.0"
    open_source_license: "Not open source"
    timezone: "America/Panama"
    windows: "n"
    use_pycharm: "y"
    use_docker: "y"
    postgresql_version: "12.3"
    js_task_runner: "None"
    cloud_provider: "AWS"
    mail_service: "Mailgun"
    use_async: "n"
    use_drf: "y"
    custom_bootstrap_compilation: "n"
    use_compressor: "n"
    use_celery: "y"
    use_mailhog: "y"
    use_sentry: "n"
    use_whitenoise: "n"
    use_heroku: "y"
    ci_tool: "Github"
    keep_local_envs_in_vcs: "y"
    debug: "n"
    allow_suscription: "n"
#extra_context:
#
cookiecutters_dir: "/Users/luiscberrocal/PycharmProjects/django_ansible_config/cookiecutter"