- name: Configuring Cookiecutter
  hosts: localhost
  vars:
    full_name: "Luis Carlos Berrocal C."
    email: "luis.berrocal.1942@gmail.com"
    github_username: "luiscberrocal"
    project_name: "Demo project"
    pycharm_project_folder: "{{ansible_facts.env.HOME}}/PycharmProjects"
  tasks:
    - name: Print some available facts
      debug:
        msg: "OS: {{ ansible_distribution }}, {{ ansible_distribution_release }}"
    - name: Print env
      debug:
        msg: "Environment: {{ ansible_facts.env.PWD }}"
    - name: Updating cookiecutter configuration
      template:
        src: "../templates/cookiecutter-config.yml.j2"
        dest: "../cookiecutter/cookiecutter-config.yml"

    - name: Install Cookiecuter
      pip:
        name: cookiecutter
        #virtualenv: "{{pycharm_project_folder}}/django_ansible_config/venv"
        #virtualenv_command: virtualenv-2.7
