- name: Install github cli
  hosts: localhost
  vars:
    username: "{{ ansible_facts.env.USER }}"
  tasks:
    - name: Print all available facts
      debug:
        msg: "OS: {{ ansible_distribution }}, {{ ansible_distribution_release }} user {{ username }}"
    - name: Install Github CLI on Mac
      shell: brew install gh
      become: yes
      become_user: "{{username}}"
      when: ansible_distribution == "MacOsx"

    - name: Add Ubuntu key on Pop!_OS
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: C99B11DEB97541F0
        state: present
      become: yes
      when: ansible_distribution == "Pop!_OS"

    - name: Add github repository into sources list
      become: yes
      apt_repository:
        repo: "deb https://cli.github.com/packages {{ansible_distribution_release}} main"
        state: present
        update_cache: no
      register: apt_repository
      when: ansible_distribution == "Pop!_OS"

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install github cli, virtualenv
      become: yes
      apt:
        name: ["gh"]
        state: present
      when: ansible_distribution == "Pop!_OS"

#    - name: Install Cookiecuter
#      pip:
#        name: cookiecutter
#        virtualenv: "{{current_user_data.home}}/PycharmProjects/django_ansible_config/venv"
#        #virtualenv_command: virtualenv-2.7

#sudo apt install software-properties-common and trying these steps again.
#sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
#sudo apt-add-repository https://cli.github.com/packages
#sudo apt update
#sudo apt install gh
